const ah=escapeHTML;
const authorityStatus=$('#authority-status');
const authorityBody=$('#authority-body');
let authorityApproved=null;
function field(name,label,type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" required ${extra}></label>`;}
async function authorityRequest(path,method='GET',data){
 const response=await fetch(path,{method,cache:'no-store',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});
 const result=await response.json();if(!response.ok)throw new Error(result.error||(response.status===401?'Sign in using the button above to continue.':'Unable to load. Please retry.'));return result;
}
async function openAuthority(){
 showScreen('authority-screen');authorityStatus.textContent='Send a report to the MAUSAM team. No sign-in needed.';
 authorityBody.innerHTML=`<form id="report-form" class="authority-form"><p class="small muted">Contact details and files are private to the team and your receipt holder. Your name and organisation are self-declared. Reports do not replace verified forecasts.</p>${field('name','Your name','text','maxlength="100"')}${field('organisation','Organisation / department','text','maxlength="150"')}${field('email','Contact email','email','maxlength="200"')}${field('title','Report title','text','maxlength="120"')}${field('location','Location / district','text','maxlength="150"')}${field('expiresAt','Expiry date and time (your device time)','datetime-local')}<label>Report details<textarea name="note" required minlength="10" maxlength="2000" rows="4"></textarea></label><label>Attachment (optional, maximum 500 KB)<input name="attachment" type="file" accept=".pdf,.png,.jpg,.jpeg,.txt"></label><button class="primary">Submit report</button></form><h2>Your submissions on this device</h2><div id="reports-list"></div><button id="team-inbox" class="weather-link">Open private team inbox</button>`;
 $('#report-form').onsubmit=submitReport;$('#team-inbox').onclick=loadTeamInbox;loadLocalReports();
}
function reportCard(row){const d=typeof row.details==='string'?JSON.parse(row.details):row.details;const card=document.createElement('article');card.className='approval-card';card.innerHTML=`<h2>${ah(d.title)}</h2><p>${ah(d.name)} · ${ah(d.organisation)}</p><p>${ah(d.email)}</p><p>${ah(d.location)}</p><p class="update-note">${ah(d.note)}</p><p>Submitted: ${ah(new Date(row.created_at).toLocaleString())}</p><p>Expires: ${ah(new Date(row.expires_at).toLocaleString())}</p><p>${Date.parse(row.expires_at)<=Date.now()?'Expired':'Received · awaiting team review'}</p><p>File: ${ah(d.fileName||'No attachment')}${d.fileName?' · '+d.fileBytes+' bytes':''}</p><p class="small">Reference: ${ah(row.id)}</p>`;return card;}
function privateCode(prefix){return prefix+Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function submitReport(e){e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;authorityStatus.textContent='Uploading…';try{const d=Object.fromEntries(new FormData(e.target));const file=d.attachment;delete d.attachment;d.expiresAt=new Date(d.expiresAt).toISOString();d.receipt=privateCode('r_');if(file?.size){if(file.size>500000)throw new Error('Maximum attachment size is 500 KB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const n of bytes)binary+=String.fromCharCode(n);d.file={name:file.name,type:file.type||'text/plain',base64:btoa(binary)};}const row=await authorityRequest('/api/submissions','POST',d);const receipts=JSON.parse(localStorage.getItem('mausam-receipts')||'[]');receipts.unshift({id:row.id,receipt:d.receipt});localStorage.setItem('mausam-receipts',JSON.stringify(receipts.slice(0,30)));authorityStatus.textContent='Received by the team. Your report and expiry are shown below.';e.target.reset();await loadLocalReports();}catch(e){authorityStatus.textContent=e.message;}finally{b.disabled=false;}}
async function loadLocalReports(){const node=$('#reports-list');node.replaceChildren();const saved=JSON.parse(localStorage.getItem('mausam-receipts')||'[]');if(!saved.length)node.textContent='No submissions from this device yet.';for(const r of saved){try{const response=await fetch('/api/submissions?id='+encodeURIComponent(r.id),{headers:{'X-Receipt':r.receipt},cache:'no-store'});const row=await response.json();if(!response.ok)throw new Error(row.error);const card=reportCard(row);attachDownload(card,row);node.append(card);}catch(e){const p=document.createElement('p');p.textContent=e.message;node.append(p);}}}
function attachDownload(card,row){if(!row.attachment)return;const b=document.createElement('button');b.className='weather-link';b.textContent='Download attachment';b.onclick=()=>{const d=JSON.parse(row.details);const bytes=Uint8Array.from(atob(row.attachment),x=>x.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));const a=document.createElement('a');a.href=url;a.download=d.fileName;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};card.append(b);}
async function loadTeamInbox(){try{const data=await authorityRequest('/api/submissions?inbox=1');const node=$('#reports-list');node.replaceChildren();authorityStatus.textContent='Private team inbox · latest 100 submissions';if(!data.submissions.length)node.textContent='No reports received yet.';for(const row of data.submissions){const card=reportCard(row);const b=document.createElement('button');b.className='weather-link';b.textContent='Load attachment';b.onclick=async()=>{try{const full=await authorityRequest('/api/submissions?id='+row.id);attachDownload(card,full);b.remove();}catch(e){authorityStatus.textContent=e.message;}};card.append(b);node.append(card);}}catch(e){authorityStatus.textContent=e.message+' The owner can also view records in Site settings → Database → disaster_submissions.';}}
$('#manage-authority').addEventListener('click',openAuthority);
function renderAuthorityApplication(){
 authorityBody.innerHTML=`<form id="authority-application" class="authority-form">
 <p class="small muted">Provide a work credential reference, not a password or an identity-document scan. Only the site administrator can view these details. Approval is a manual affiliation check.</p>
 ${field('name','Full name','text','maxlength="100"')}${field('organisation','Organisation','text','maxlength="150"')}${field('designation','Designation','text','maxlength="100"')}${field('workEmail','Official work email','email','maxlength="200"')}${field('credentialRef','Employee / authority credential reference','text','maxlength="100"')}${field('officialURL','Official staff directory or verification page','url','placeholder="https://…" maxlength="500"')}${field('jurisdiction','District / jurisdiction','text','maxlength="150"')}
 <p class="small muted">Define the centre and radius of your requested publishing area.</p><div class="form-grid">${field('latitude','Latitude','number','min="-90" max="90" step="any"')}${field('longitude','Longitude','number','min="-180" max="180" step="any"')}</div>${field('radiusKm','Area radius (km)','number','min="1" max="100" step="any"')}
 <button class="primary">Submit for approval</button></form>`;
 $('#authority-application').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const v=Object.fromEntries(new FormData(e.target));for(const key of ['latitude','longitude','radiusKm'])v[key]=Number(v[key]);try{await authorityRequest('/api/authority','POST',v);await openAuthority();}catch(error){authorityStatus.textContent=error.message;button.disabled=false;}});
}
function renderAuthorityEditor(){
 const a=authorityApproved;
 authorityBody.innerHTML=`<div class="approval-card"><strong>${ah(a.organisation)}</strong><p>Approved area: ${ah(a.jurisdiction)} · ${a.radiusKm} km radius</p><p class="small">Contributor access approved by the MAUSAM administrator. This does not certify forecast accuracy.</p></div><button id="sample-operations" class="weather-link">View sample operations dashboard →</button>
 <form id="authority-update" class="authority-form"><h2>Publish a local forecast update</h2><p class="small muted">Your name, organisation, source and expiry will appear publicly. Original provider data stays visible.</p>
 ${field('title','Update title','text','minlength="4" maxlength="120"')}${field('location','Location label','text','maxlength="150"')}
 <div class="form-grid">${field('latitude','Latitude','number',`value="${a.latitude}" min="-90" max="90" step="any"`)}${field('longitude','Longitude','number',`value="${a.longitude}" min="-180" max="180" step="any"`)}</div>${field('radiusKm','Coverage radius (km)','number',`value="${a.radiusKm}" min="1" max="100" step="any"`)}
 <div class="form-grid">${field('temperature','Temperature (°C)','number','min="-70" max="60" step="0.1"')}${field('wind','Wind (km/h)','number','min="0" max="400" step="0.1"')}</div>${field('rainChance','Rain probability (%)','number','min="0" max="100"')}${field('validHours','Valid for (hours)','number','min="1" max="24" value="3"')}${field('source','Evidence / bulletin URL','url','placeholder="https://…" maxlength="500"')}
 <label>Reason and supporting details<textarea name="note" required minlength="10" maxlength="1500" rows="4"></textarea></label><button class="primary">Publish update</button></form><h2 class="weather-section-title">Your update history</h2><div id="authority-history"></div>`;
 $('#sample-operations').addEventListener('click',()=>{renderDashboard('Operations');showScreen('dashboard-screen');});
 $('#authority-update').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const v=Object.fromEntries(new FormData(e.target));for(const key of ['latitude','longitude','radiusKm','temperature','wind','rainChance','validHours'])v[key]=Number(v[key]);try{await authorityRequest('/api/authority/updates','POST',v);authorityStatus.textContent='Published. Users in the covered area can see your update until it expires or is withdrawn.';e.target.reset();await loadAuthorityHistory();}catch(error){authorityStatus.textContent=error.message;}finally{button.disabled=false;}});
 loadAuthorityHistory();
}
async function loadAuthorityHistory(){
 try{const data=await authorityRequest('/api/authority/updates?mine=1');const node=$('#authority-history');if(!node)return;node.innerHTML=data.updates.length?'':'<p class="muted">No updates published yet.</p>';for(const row of data.updates){const p=JSON.parse(row.payload);const card=document.createElement('article');card.className='approval-card';card.innerHTML=`<strong>${ah(p.title)}</strong><p class="small">${ah(new Date(row.created_at).toLocaleString())} · ${row.withdrawn_at?'Withdrawn':new Date(row.expires_at)<=new Date()?'Expired':'Active'}</p>`;if(!row.withdrawn_at){const b=document.createElement('button');b.className='weather-link';b.textContent='Withdraw update';b.addEventListener('click',async()=>{b.disabled=true;try{await authorityRequest('/api/authority/updates','DELETE',{id:row.id});await loadAuthorityHistory();}catch(e){authorityStatus.textContent=e.message;b.disabled=false;}});card.append(b);}node.append(card);}}
 catch(e){authorityStatus.textContent=e.message;}
}
async function renderAuthorityReviews(){
 authorityStatus.textContent='Loading applications…';
 try{const data=await authorityRequest('/api/authority/review');authorityBody.replaceChildren();authorityStatus.textContent='Check each affiliation and coverage area independently before approval. Work-email text alone is not verification.';
 const back=document.createElement('button');back.className='weather-link';back.textContent='Back to workspace';back.onclick=openAuthority;authorityBody.append(back);
 if(!data.applications.length){const p=document.createElement('p');p.textContent='No applications yet.';authorityBody.append(p);}
 for(const row of data.applications){const a=JSON.parse(row.details);const card=document.createElement('article');card.className='approval-card';card.innerHTML=`<h2>${ah(a.name)}</h2><p>${ah(a.organisation)} · ${ah(a.designation)}</p><p>${ah(a.workEmail)}</p><p>Credential: ${ah(a.credentialRef)}</p><p>Area: ${ah(a.jurisdiction)} · ${a.latitude}, ${a.longitude} · ${a.radiusKm} km</p><a href="${ah(a.officialURL)}" target="_blank" rel="noopener">Verification source ↗</a><p>Status: ${ah(row.status)}</p>`;
 const label=document.createElement('label');label.className='review-confirm';const checkbox=document.createElement('input');checkbox.type='checkbox';label.append(checkbox,document.createTextNode(' I independently checked this affiliation and coverage area.'));card.append(label);
 for(const [decision,title]of [['approved','Approve'],['rejected','Reject'],['revoked','Revoke access']]){const b=document.createElement('button');b.className='weather-link';b.textContent=title;b.addEventListener('click',async()=>{if(decision==='approved'&&!checkbox.checked){authorityStatus.textContent='Complete the affiliation check before approving.';return;}b.disabled=true;try{await authorityRequest('/api/authority/review','POST',{userId:row.user_id,status:decision,confirmed:checkbox.checked});await renderAuthorityReviews();}catch(e){authorityStatus.textContent=e.message;b.disabled=false;}});card.append(b);}authorityBody.append(card);}
 }catch(e){authorityStatus.textContent=e.message;}
}
let authorityWeatherRequest=0;
async function loadAuthorityWeather(){
 const id=++authorityWeatherRequest;const container=$('#authority-weather');if(!container)return;
 container.replaceChildren();
 try{const {latitude,longitude}=weatherState.place;const data=await authorityRequest(`/api/authority/updates?lat=${latitude}&lon=${longitude}`);if(id!==authorityWeatherRequest)return;
 for(const u of data.updates){const card=document.createElement('article');card.className='authority-weather-card';card.dataset.expiry=u.expiresAt;card.innerHTML=`<p class="small">LOCAL UPDATE · APPROVED CONTRIBUTOR</p><h2>${ah(u.title)}</h2><p>${ah(u.location)}</p><div class="weather-metrics"><div class="metric"><span>Temperature</span><strong>${temperature(u.temperature)}</strong></div><div class="metric"><span>Wind</span><strong>${number(u.wind,' km/h')}</strong></div></div><p>Rain probability: ${number(u.rainChance,'%')}</p><p class="update-note">${ah(u.note)}</p><p class="small">${ah(u.author)} · ${ah(u.organisation)}</p><p class="small">Issued ${ah(new Date(u.createdAt).toLocaleString())}<br>Valid until ${ah(new Date(u.expiresAt).toLocaleString())}</p><a href="${ah(u.source)}" target="_blank" rel="noopener">View supporting source ↗</a><p class="small muted">Contributor-provided revision; original forecast remains below.</p>`;container.append(card);}
 }catch{if(id===authorityWeatherRequest)container.innerHTML='<p class="small muted">Local authority updates are unavailable. Provider weather is shown below.</p>';}
}
setInterval(()=>{document.querySelectorAll('[data-expiry]').forEach(card=>{if(Date.parse(card.dataset.expiry)<=Date.now())card.remove();});if(!document.hidden&&!$('#weather-screen').hidden)loadAuthorityWeather();},60000);
