let preferenceAccount=null,preferenceCity=null,preferenceCityRequest=0;
function storedSettings(){try{return JSON.parse(localStorage.getItem('mausam-settings')||'{}');}catch{return {};}}
function applyPreferences(s){language=s.language;profile=s.profile;weatherState.unit=s.unit;weatherState.place=s.place;weatherState.controller?.abort();weatherState.data=null;weatherState.fetched=0;localStorage.setItem('mausam-settings',JSON.stringify(s));const radio=document.querySelector(`input[name="language"][value="${language}"]`);if(radio)radio.checked=true;$('#next').disabled=false;renderProfiles();$('#unit-toggle').textContent=s.unit==='C'?'°C / °F':'°F / °C';}
function preferenceToken(){return sessionStorage.getItem('mausam-account-session')||'';}
async function accountRequest(path,method='GET',body){const response=await fetch(path,{method,cache:'no-store',headers:{'Content-Type':'application/json','Authorization':'Bearer '+preferenceToken()},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok){if(response.status===401){sessionStorage.removeItem('mausam-account-session');preferenceAccount=null;renderPreferenceAccount();}throw new Error(data.error||'Could not complete the request. Retry.');}return data;}
function renderPreferenceAccount(){const node=$('#profile-account-info');node.replaceChildren();$('#profile-account-form').hidden=!!preferenceAccount;if(preferenceAccount){const p=document.createElement('p');p.textContent='Signed in as '+preferenceAccount.username;const b=document.createElement('button');b.className='weather-link';b.textContent='Sign out';b.onclick=async()=>{try{await accountRequest('/api/profile-session','POST',{action:'logout'});sessionStorage.removeItem('mausam-account-session');preferenceAccount=null;renderPreferenceAccount();$('#saved-preferences').textContent='Sign in to view your saved setups.';$('#profile-account-status').textContent='Signed out.';}catch(e){$('#profile-account-status').textContent=e.message;}};node.append(p,b);}$('#preferences-form button[type="submit"], #preferences-form button.primary').disabled=!preferenceAccount;}
async function checkPreferenceAccount(){try{if(!preferenceToken()){preferenceAccount=null;renderPreferenceAccount();return;}const d=await accountRequest('/api/profile-session');preferenceAccount=d.user;renderPreferenceAccount();await loadPreferenceSets();}catch(e){$('#profile-account-status').textContent=e.message;}}
function openPreferences(){showScreen('preferences-screen');const f=$('#preferences-form');f.elements.language.value=language||'en';f.elements.profile.value=profile||'citizen';f.elements.unit.value=weatherState.unit;f.elements.rainAlerts.checked=storedSettings().rainAlerts===true;preferenceCity={...weatherState.place};$('#preferred-city').textContent='Selected city: '+preferenceCity.name;$('#preference-city-results').replaceChildren();checkPreferenceAccount();}
$('#preferences-shortcut').onclick=openPreferences;
window.addEventListener('hashchange',()=>{if(location.hash==='#preferences')openPreferences();});window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===window.parent&&e.data?.action==='open-preferences')openPreferences();});
$('#profile-account-form').onsubmit=async e=>{e.preventDefault();const f=e.target,buttons=f.querySelectorAll('button');buttons.forEach(b=>b.disabled=true);$('#profile-account-status').textContent='Please wait…';try{const d=await accountRequest('/api/profile-session','POST',{action:e.submitter?.value||'login',username:f.elements.username.value,password:f.elements.password.value});sessionStorage.setItem('mausam-account-session',d.token);preferenceAccount=d.user;f.elements.password.value='';renderPreferenceAccount();$('#profile-account-status').textContent='Your saved preferences are available on every device where you sign in.';await loadPreferenceSets();}catch(e){$('#profile-account-status').textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}};
async function loadPreferenceSets(){const node=$('#saved-preferences');if(!preferenceAccount){node.textContent='Sign in to view your saved setups.';return;}node.textContent='Loading your preferences…';try{const data=await accountRequest('/api/preference-sets');node.replaceChildren();if(!data.sets.length)node.innerHTML='<p class="muted">No saved preferences yet. Create your first setup below.</p>';for(const set of data.sets){const s=set.settings,card=document.createElement('article');card.className='preset-card';card.innerHTML=`<div class="preset-symbol" aria-hidden="true">${s.profile==='farmer'?'🌾':s.profile==='authority'?'📋':'⌂'}</div><div><h3>${escapeHTML(set.name)}</h3><p>${escapeHTML(s.place.name)}</p><p class="small muted">${escapeHTML(s.profile)} · ${escapeHTML(s.language.toUpperCase())} · °${s.unit}</p><p class="small muted">Saved ${escapeHTML(new Date(set.updated_at).toLocaleString())}</p></div>`;const actions=document.createElement('div');actions.className='preset-actions';const load=document.createElement('button');load.className='primary';load.textContent='Load preference';load.onclick=()=>{applyPreferences(s);$('#preferences-status').textContent='Loaded '+set.name+'.';if(s.profile==='authority'){openAuthority();}else{openWeather('preferences-screen');}};const del=document.createElement('button');del.className='weather-link';del.textContent='Delete';del.onclick=async()=>{if(!confirm('Delete saved preference “'+set.name+'”?'))return;del.disabled=true;try{await accountRequest('/api/preference-sets','DELETE',{id:set.id});await loadPreferenceSets();}catch(e){$('#preferences-status').textContent=e.message;del.disabled=false;}};actions.append(load,del);card.append(actions);node.append(card);}}catch(e){node.textContent=e.message;}}
$('#refresh-presets').onclick=()=>checkPreferenceAccount();
$('#preferences-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button.primary');button.disabled=true;try{const f=e.target.elements;const settings={language:f.language.value,profile:f.profile.value,unit:f.unit.value,place:preferenceCity||weatherState.place,rainAlerts:f.rainAlerts.checked};await accountRequest('/api/preference-sets','POST',{name:f.name.value.trim(),settings});$('#preferences-status').textContent='Preference saved. Select Load to use it.';f.name.value='';await loadPreferenceSets();}catch(e){$('#preferences-status').textContent=e.message;}finally{button.disabled=!preferenceAccount;}};
$('#find-preference-city').onclick=async()=>{const q=$('#preference-city-search').value.trim(),node=$('#preference-city-results'),id=++preferenceCityRequest;if(q.length<2){node.textContent='Type at least two characters.';return;}node.textContent='Searching…';try{const r=await fetch('https://geocoding-api.open-meteo.com/v1/search?'+new URLSearchParams({name:q,count:'5',language:'en',format:'json'}));if(!r.ok)throw new Error('City search unavailable. Retry.');const data=await r.json();if(id!==preferenceCityRequest)return;node.replaceChildren();if(!data.results?.length)node.textContent='No city found. Try a nearby town.';for(const city of data.results||[]){const b=document.createElement('button');b.type='button';const name=[city.name,city.admin1,city.country].filter(Boolean).join(', ');b.textContent=name;b.onclick=()=>{preferenceCity={name,latitude:city.latitude,longitude:city.longitude};$('#preferred-city').textContent='Selected city: '+name;node.replaceChildren();};node.append(b);}}catch(e){if(id===preferenceCityRequest)node.textContent=e.message;}};
try{const s=storedSettings();if(s.language)applyPreferences(s);localStorage.removeItem('mausam-recovery');}catch{}
if(location.hash==='#preferences')openPreferences();
